const enUS = {
  'welcome' : 'Welcome to the MMP App!',
  'create_word': 'Create a new word.',
  'view_all_words': "View all words.",
  'settings': "Changing language",
  'exit': "Exit the program.",
  'error': "Error command entered",
  'new_word_name': "Enter a new word: ",
  'file_error': "The word entered was created earlier, please try again.",
  'write_word': "Enter translation:",
  'save': 'save',
  'word_save': "Word successfully saved!",
  'number_word': "Enter the Word number",
  'delete_all': "Delete all words",
  'delete_selected': "Selective deletion",
  'no_word': "No words yet!",
  'back_to_home': "Return to the main menu.",
  'enter_word_number': "Enter the Word number: ",
  "update": "Edit translation",
  "delete": "Delete",
  "back_to": "Back to",
  'previous_word': "Previous word:",
  'success_delete_all': "Selected words were deleted successfully!",
  'select_file': "Enter the number of memorized words by selecting it:",
  'edit_word' : "Make changes: ",
  'sure' : "Are you sure?",
  'yes' : "yes",
  'no' : "no",
  "stop_to_delete" : "Enter the word 'save' to complete the operation",
  "write_description" : "Enter description: ",
  "write_example" : "Enter example to word: ",
  "test" : "Test",
  "missing_word": "Try to find missed letter from word",
  "correct_answers": "Number of correct answers",
  "percent" : "Correct answers in percentage",
  "update_lang" : "Select a language\n",
  "which_letter": "Which letter was omitted?",
  "second_game": "Find the translation of the word",
  'not_found': "Object is not found",
  "return_main":"Type «exit» to end the test",
  "length_word_error":"Length of the word shouldn't be less then 2",
  "deleted_successfully":"All words deleted successfully",
  "length_not_enough":"For using this test stored words shouldn't be less than 4",
  "number_of_words":"The number of saved words => ",

};