const uzUZ = {
  'welcome' : 'MMP Appga Xush Kelibsiz!',
  'create_word': 'Yangi so\'z qo\'shish.',
  'view_all_words': "Barcha so'zlarni ko'rish.",
  'settings': "Tilni o'zgartirish",
  'exit': "Dasturdan chiqish.",
  'error': "Xato buyruq kiritildi",
  'new_word_name': "Yangi so'zni kiriting: ",
  'file_error': "Kiritilgan so'z oldin yaratilgan, Iltimos qayta urunib ko'ring.",
  'write_word': "Tarjimasini kiriting: ",
  'save': 'save',
  'word_save': "So'z muvaffaqiyatli saqlandi!",
  'number_word': "So'z raqamini kiriting",
  'delete_all': "Barcha so'zlarni o'chirish",
  'delete_selected': "Tanlab o'chirish",
  'no_word': "Hozircha so'zlar mavjud emas!",
  'back_to_home': "Bosh menuga qaytish.",
  'enter_word_number': "So'z raqamini kiriting: ",
  "update": "Tarjimani o'zgartirish",
  "delete": "O'chirish",
  "back_to": "Ortga qaytish",
  'previous_word': "Avvalgi so'z:",
  'success_delete_all': "Tanlangan so'zlar muvoffaqiyatli o'chirildi!",
  'select_file': "Yodlangan so'zlarni raqamini tanlab kiriting:",
  'edit_word' : "O'zgarishni kiriting: ",
  'sure' : "Ishonchingiz komilmi?",
  'yes' : "ha",
  'no' : "yo'q",
  "stop_to_delete" : "Amalni tugatish uchun 'save' so'zini kiriting: ",
  "write_description" : "So'zning tavsifini kiriting: ",
  "write_example" : "So'zga misol kiriting: ",
  "test" : "Test",
  "missing_word": "So'zdan tushib qolgan harfni topish",
  "correct_answers": "To'g'ri javoblar soni",
  "percent" : "To'g'ri javoblar foizda",
  "update_lang" : "Tilni tanlang\n",
  "which_letter": "Qaysi harf kiritilishi kerak?",
  "second_game": "So'zning tarjimasini topish",
  'not_found': "Ob'ekt topilmadi",
  "return_main":"Testni yakunlash uchun «exit» ni bosing",
  "length_word_error":"so'z uzunligi 2 dan katta bo'lishi kerak",
  "deleted_successfully":"Barcha so'zlar muvaffaqiyatli o'chirildi",
  "length_not_enough":"Ushbu testdan foydalanish uchun saqlangan so'zlar 4 ta dan kam bo'lmasligi kerak",
  "number_of_words":"Sizdan saqlangan so'zlar soni => ",
};